services:
  api:
    container_name: tekra_boy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - openvpn
    command: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8000"

  openvpn:
    image: kylemanna/openvpn
    container_name: vpn_server
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/tcp"
    volumes:
      - openvpn_data:/etc/openvpn
#      - ./init-openvpn.sh:/init-openvpn.sh
#    env_file:
#      - .env
#    entrypoint: ["/bin/sh", "-c", "/init-openvpn.sh"]
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  openvpn_data: