services:
  api:
    container_name: tekra_boy
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8000:8000"
    networks:
      - backend
    depends_on:
      - openvpn  # додаємо залежність від openvpn
    command: sh -c "uvicorn src.fast_app:app --host 0.0.0.0 --port 8000"

  openvpn:
    image: kylemanna/openvpn
    container_name: vpn_server
    cap_add:
      - NET_ADMIN
    ports:
      - "1194:1194/udp"
    volumes:
      - openvpn_data:/etc/openvpn
    networks:
      - backend
    environment:
      - DEBUG=1

networks:
  backend:
    driver: bridge

volumes:
  openvpn_data:
